### ISSUE TITLE
Support for ratelimit-reset

### ISSUE THREAD

**Issue by ioggstream** [envoyproxy/ratelimit#165] opened 2020-08-07 15:17 UTC
## I expect

The `ratelimit` service to expose the data required to populate the `x-ratelimit-reset` header

## Instead

They are not exposed

## Reproduce

When I run 

```
git clone https://github.com/ioggstream/envoy-ratelimit-quickstart
cd envoy-ratelimit-quickstart
docker-compose up -d
curl -i http://localhost:8080/service/1
```

I get

```
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 91
server: envoy
date: Fri, 07 Aug 2020 15:15:03 GMT
x-envoy-upstream-service-time: 11
x-ratelimit-limit: 50, 50;w=60
x-ratelimit-remaining: 49
x-ratelimit-reset: 0

Hello from behind Envoy (service 2)! hostname: 5eac71206ff9 resolvedhostname: 192.168.32.2
```
 
I expect

```
x-ratelimit-reset: 49
```

Instead

```
x-ratelimit-reset: 0
```

## Note

Thanks for implementing ratelimit draft in envoy :D

**Comment by mattklein123** [comment] 2020-08-07 16:29
I believe @Pchelolo is going to implement this.

**Comment by Pchelolo** [comment] 2020-08-07 16:31
Yup, just waiting for the new version of go-control-plane to be cut.

**Comment by ioggstream** [comment] 2020-08-08 22:20
Yes, but I thought an issue was worth opening :) Great work folks! :clap:

**Comment by ioggstream** [comment] 2020-09-11 08:03
Hi @Pchelolo, are there any news on the control plane release?

**Comment by Pchelolo** [comment] 2020-09-11 14:21
> Hi @Pchelolo, are there any news on the control plane release?

Hi, I'm not a maintainer, so I don't know. Maybe @mattklein123 can tell us when is a new release of the go-control-plane scheduled.

**Comment by mattklein123** [comment] 2020-09-11 16:00
I don't know what the release strategy of go-control-plane is. I think most people just import it by SHA. Can you inquire in that project?

**Comment by ioggstream** [comment] 2020-10-12 10:10
Hi @kyessenov, do you have any hints about the release date of the new go-control-plane?
Thanks for your support :)

**Comment by kyessenov** [comment] 2020-10-12 16:36
@ioggstream you can always use a particular SHA, `go get ..@SHA`. It's usually stable at head.

**Comment by mattklein123** [comment] 2020-10-19 23:38
> @ioggstream you can always use a particular SHA, go get ..@SHA. It's usually stable at head.

+1

**Comment by ioggstream** [comment] 2020-10-20 20:14
@Pchelolo can we use a `@sha` as a base of the control plane? Let me know how I can help the implementation (not an envoy expert, but if you point out the implementation strategy and the files to edit I can try).

**Comment by Pchelolo** [comment] 2020-10-20 20:16
My colleague @clarakosi is working on it, she will submit a request shortly.

**Comment by colek319** [comment] 2020-11-02 21:25
Whats the status on this issue? This test is failing on the most recent commit. 
```
--- FAIL: TestBasicAuthConfigWithRedisCluster (4.64s)
    --- FAIL: TestBasicAuthConfigWithRedisCluster/WithPerSecondRedisAuth (1.15s)
        common.go:77: 
                Error Trace:    common.go:77
                                                        integration_test.go:342
                Error:          Should be true
                Test:           TestBasicAuthConfigWithRedisCluster/WithPerSecondRedisAuth
                Messages:       These two protobuf messages are not equal:
                                expected: overall_code:OK  statuses:{code:OK  current_limit:{requests_per_unit:20  unit:MINUTE}  limit_remaining:8  duration_until_reset:{seconds:59}}
                                actual:  overall_code:OK  statuses:{code:OK  current_limit:{requests_per_unit:20  unit:MINUTE}  limit_remaining:8  duration_until_reset:{seconds:60}}
```

**Comment by ysawa0** [comment] 2020-11-02 21:39
I noticed yesterday that the builds for master have been broken since #179 was merged. Oddly the #182 merge test failed for a different reason. It's strange that the builds for PRs pass but the builds for master fails consistently. I see that they both ultimately call the same `make docker_tests`?

I think #179 and #182 both introduced different regressions. Not sure what the former's issue is but #182's tests don't look to be deterministic due to the `duration_until_reset`.

**Comment by mattklein123** [comment] 2020-11-03 00:03
Yeah seems like main branch is broken and/or has flakes. @ysawa0 would you be interested in taking a look at fixing? I'm going to close this issue as it is actually fixed.

**Closed by mattklein123** 2020-11-03 00:03 UTC
Labels: help wanted
